<script setup lang="ts">
import { profile } from '~/data/profile'

const props = withDefaults(
  defineProps<{
    size?: 176 | 240
    /** Set on the above-the-fold instance so it is not lazy-loaded. */
    eager?: boolean
  }>(),
  { size: 176, eager: false },
)

/**
 * Derivatives are pre-generated by scripts/generate-images.mjs, so the 1× and
 * 2× widths here must exist on disk. Explicit width/height plus a fixed aspect
 * ratio means the space is reserved before the file arrives — no layout shift.
 */
const retina = computed(() => props.size * 2)

// public/ is served under app.baseURL on a project Pages site, so a bare
// "/img/..." would resolve to the domain root and 404.
const base = useRuntimeConfig().app.baseURL
const src = (w: number, ext: string) => `${base}img/akash-chauhan-${w}.${ext}`
</script>

<template>
  <picture>
    <source
      type="image/avif"
      :srcset="`${src(size, 'avif')} 1x, ${src(retina, 'avif')} 2x`"
    >
    <source
      type="image/webp"
      :srcset="`${src(size, 'webp')} 1x, ${src(retina, 'webp')} 2x`"
    >
    <img
      :src="src(size, 'jpg')"
      :srcset="`${src(size, 'jpg')} 1x, ${src(retina, 'jpg')} 2x`"
      :width="size"
      :height="size"
      :alt="`${profile.name}, ${profile.role} at ${profile.company}`"
      :loading="eager ? 'eager' : 'lazy'"
      :fetchpriority="eager ? 'high' : 'auto'"
      decoding="async"
      class="rounded-card border border-ink-100 bg-ink-50 object-cover"
      :style="{ width: `${size}px`, height: `${size}px` }"
    >
  </picture>
</template>
