/**
 * Build-time GitHub fetch → data/github.json
 *
 * Run before `nuxt generate`. Never runs in the browser.
 *
 * Deliberate choices:
 *  - "Stars" means stars OTHER people gave my non-fork repos, summed here.
 *    The 312 on the GitHub profile page is repos Akash starred — showing that
 *    as an achievement would be misleading, so it is never read or written.
 *  - Forks are excluded from every total. Someone else's stars are not mine.
 *  - On failure the existing data/github.json is left untouched and the build
 *    continues with the last good snapshot, rather than publishing zeroes.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = resolve(ROOT, 'data/github.json')
const USER = 'Akash52'

/** Repos that signal student-era work. Never featured, still counted in totals. */
const NEVER_FEATURE = new Set(['code-daily', 'trip-planning-chatbot'])

/**
 * Featured repos in display order, with a hand-written sentence each — the
 * GitHub blurbs are inconsistent and some are empty. Stars, forks, language and
 * last-updated always come from the API, never from here.
 */
const FEATURED = [
  {
    name: 'msal-with-nuxt3',
    blurb:
      'A working Microsoft Entra ID (Azure AD) sign-in flow for Nuxt 3, using MSAL. Covers the bits the official docs skip: token refresh, route guards and SSR.',
  },
  {
    name: 'awesome-Javascript-collection',
    blurb: 'Small vanilla JavaScript projects, each one built to teach a single idea.',
  },
  {
    name: 'awesome-javascript-concepts',
    blurb: 'JavaScript language concepts written out as runnable examples rather than definitions.',
  },
  {
    name: 'awesome-almost-stack',
    blurb: 'TypeScript experiments and stack spikes.',
  },
]

const token = process.env.GITHUB_TOKEN
const headers = {
  Accept: 'application/vnd.github+json',
  'User-Agent': `${USER}-portfolio-build`,
  ...(token ? { Authorization: `Bearer ${token}` } : {}),
}

async function gh(path) {
  const res = await fetch(`https://api.github.com${path}`, { headers })
  if (!res.ok) {
    throw new Error(`GitHub ${path} → ${res.status} ${res.statusText}`)
  }
  return res.json()
}

/** A repo worth featuring has a description and a README. */
async function hasReadme(name) {
  const res = await fetch(`https://api.github.com/repos/${USER}/${name}/readme`, { headers })
  return res.ok
}

async function main() {
  if (!token) {
    console.warn('[github] No GITHUB_TOKEN — using the 60 req/hour anonymous limit.')
  }

  const [user, repos] = await Promise.all([
    gh(`/users/${USER}`),
    gh(`/users/${USER}/repos?per_page=100&sort=updated`),
  ])

  // Everything below is computed from repos Akash actually owns.
  const owned = repos.filter((r) => !r.fork && !r.archived)

  const starsEarned = owned.reduce((sum, r) => sum + r.stargazers_count, 0)
  const forksEarned = owned.reduce((sum, r) => sum + r.forks_count, 0)

  const languageCounts = {}
  for (const r of owned) {
    if (r.language) {
      languageCounts[r.language] = (languageCounts[r.language] || 0) + 1
    }
  }
  const topLanguages = Object.entries(languageCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6)
    .map(([name, repoCount]) => ({ name, repoCount }))

  const byName = new Map(repos.map((r) => [r.name, r]))
  const featured = []

  for (const entry of FEATURED) {
    const repo = byName.get(entry.name)
    if (!repo) {
      console.warn(`[github] Featured repo not found or not public: ${entry.name}`)
      continue
    }
    if (NEVER_FEATURE.has(repo.name)) continue
    if (!(await hasReadme(repo.name))) {
      console.warn(`[github] Skipping ${repo.name} — no README.`)
      continue
    }
    featured.push({
      name: repo.name,
      blurb: entry.blurb,
      language: repo.language,
      stars: repo.stargazers_count,
      forks: repo.forks_count,
      updatedAt: repo.pushed_at,
      url: repo.html_url,
    })
  }

  const payload = {
    _comment:
      'Generated by scripts/fetch-github.mjs. Do not edit by hand. "starsEarned" is stars received on non-fork repos, not repos starred by Akash.',
    fetchedAt: new Date().toISOString(),
    source: 'GitHub REST API',
    profileUrl: user.html_url,
    publicRepos: user.public_repos,
    followers: user.followers,
    starsEarned,
    forksEarned,
    topLanguages,
    featured,
  }

  await mkdir(dirname(OUT), { recursive: true })
  await writeFile(OUT, `${JSON.stringify(payload, null, 2)}\n`, 'utf8')

  console.log(
    `[github] ${user.public_repos} repos · ${user.followers} followers · ` +
      `${starsEarned}★ earned across ${owned.length} own repos · ${featured.length} featured`,
  )
}

main().catch(async (err) => {
  console.warn(`[github] Fetch failed: ${err.message}`)
  if (existsSync(OUT)) {
    const prev = JSON.parse(await readFile(OUT, 'utf8'))
    console.warn(`[github] Keeping the previous snapshot from ${prev.fetchedAt}.`)
    process.exit(0)
  }
  console.error('[github] No previous snapshot to fall back on. Failing the build.')
  process.exit(1)
})
